### ISSUE TITLE
XSS vulnerability

### ISSUE THREAD

**Issue by cann0010** [legumeinfo/grinlegumes#1]
See the injection vulnerability:
https://legumeinfo.org/germplasm/grin/grinlegumes?grin_acc_no=%27%3E%3C%2Fscript%3E%22%3E%3Cscript%3Eprompt%281%29%3C%2Fscript%3E&grin_taxon=

**Comment by adf-ncgr** [comment]
is this the thing we're supposed to disable anyway because grin no longer allows itself to be iframed? or is that something else I'm thinking of?

**Comment by adf-ncgr** [comment]
maybe I'm confusing it with this: https://github.com/legumeinfo/grinconnect/issues/1
but not offhand clear to me if these two repositories represent different functionalities?

**Comment by cann0010** [comment]
I think it's to be disabled. @ekcannon ?

**Comment by ekcannon** [comment]
Now that there is a germplasm search, has been for the past year, this should be removed at PeanutBase. (I'll do so). I can't speak for LegumeInfo. 

BTW, this module throws errors/warnings when clearing the Drupal cache, so if the XSS vulnerability is repaired, these should be fixed too.

**Comment by adf-ncgr** [comment]
NB: I just put a little client side validation on the input box;  I think that sorts the XSS concern (although I don't think there was really any XSS danger, if I understand correctly what I've read about it). I haven't done anything about drupal cache complaints, but we should probably review this in general as I think there are a bunch of things on the site that are gunking up our logs with TMI (at least, such is my impression whenever I am trying to get to the bottom of an actual error...)
